# Generated by Django 5.2 on 2025-04-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('inprogress', 'inprogress')], default='inprogress', max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
